INSERT INTO `amailbox_filter` (`id`, `filtervalue`, `REMOVE`, `TYPE`, `LOCATION`, `counter`, `cattegory_id`, `delaydays`) VALUES
(NULL,'lumidesk.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'jorisco.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'agnithazorg.nl', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'media-saturn.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'2dehands.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'jboss.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'dlapawelka.com.pl', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'openbare-verkopen.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'Inc.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'netlogmail.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'belfius.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'my-nwa.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'perez.it', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'hotmail.co.th', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'twoomail.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'mail.nieuwsblad.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'wtmlimited.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'marisartravel.net', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'huxley.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'24plus.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'huxley.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'medhur51.gotadsl.co.uk', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'lists.chamilo.org', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'IO-Auctions.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'yzplas.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'ecoburotic.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'nordnet.fr', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'kbs.gov.my', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'chamilo.org', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'netmeans.net', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'csr.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'prettyindustry.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'akros-solutions.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'partslist.to', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'teamdiamond.biz', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'4alpha.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'mail.ameriprise.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'progressiverecruitment.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'3d-ict.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'weathersafe.com.au', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'nmt.edu', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'aristo.com.bd', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'.MISSING-HOST-NAME.', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'mail121.us2.mcsv.net', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'swiftvalued@yahoo.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'verizon.net', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'indinox.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'miaoke.us', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'aol.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'scg.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'cmail1.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'lotto.es', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'stepstone.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'msdlt.k12.in.us', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'lobcede.ccsend.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'egm.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'webdesign-info.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'be.accent.jobs', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'sofico.be', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'oracle.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'info@marktplaats.nl', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'vegas@mlmworld.de', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'no-reply@createsend3.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'no-reply@cmail3.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'jl@juergen-liebig.de', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'Eva.Maes@tormans.net', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'info@jobagent.stepstone.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'spicynieuwsbrief@spicylemon.nl', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'sales@communitysa.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'info@yoko-ono.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'info@bekafun.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'news@mailing.bnpparibasfortis.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'nieuwsblad@promotie.nieuwsblad.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'newsletter@reply.spreadshirt.net', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'pho.vsilveer@yahoo.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'chen@mail.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'avaaz@avaaz.org', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'messages-noreply@bounce.linkedin.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'service@visaeurope.fr', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'service@globetravel.it', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'info@FED-net.org', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'pablo@jazzenede.ccsend.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'MAILER-DAEMON@secure-mail.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'sofie@3d-ict.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'chenhl@uw.edu', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'securite@service.at', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'administrador@etman.com.ar', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'noreply@belgievacature.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'no-replys@belfius.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'watchdog@helpmij.nl', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'firmajsedik@yahoo.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'advertising@itjobboard.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'teng_dai@yzplas.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'paypal@dpaypal.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'mailservice@troostwijkauctions.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'e-magazine@eventplanner.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'mailings@emails.nwruk.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'mailing@troostwijk.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'noreply@di-bag.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'haau_001@hotmail.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'belfiusbank@intl.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'info@evsound.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'newsletter@daslight.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'lezersservice@mediafin.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'micjohnson05@hotmail.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'medasq@hotmail.com', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'am@vdab.be', 'FALSE', 'EMAIL', 'GLOBAL', NULL, NULL, 1);
(NULL,'virtua.com.br ([201.74.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'virtua.com.br ([177.82.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'virtua.com.br ([187.105.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'virtua.com.br', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'@yeah.net', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'sexuel', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Vigarra', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'bigger penis', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'infoweb.ne.jp', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'sexual', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'reasonables3.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'bistargalaxy.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'gmail.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'facebook.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'123.com', 'FALSE', 'DOMAIN', 'GLOBAL', NULL, NULL, 1);
(NULL,'penis length', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'society of Urologists', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'penis length', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Erection', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'@foxmail.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'qingheLi.com ([23.95.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'emailgarage.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'do not trace any of his relatives', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Casino', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Cazino', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'bit.ly', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'zeropay', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'viagra', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Content-Type: multipart/mixed; Confirmation #', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'medicshopsthi.ru', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'onlinegfk.be', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'e-mailkings.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'v|agra', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'clients de visa carte', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'e-aanbod.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Begin uw geluk met onze grote welkom bonus', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Win veel met een ongelofelijke welkomst bonus!', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'www.cannabisciencekillscancer.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Activeren Mijn ICS', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'gentlemail.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Licensed Pharmacies', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'vip.se.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'million Dollars', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'email-brokers.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'stepstone.be', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'betaldpasbetasbpo.co', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'nieuwe beveiligingssysteem', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'bpo', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'kbs', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Gebruik de onderstaande link', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'datemy.ru', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Hi there sweet...', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'nieuw beveiligingssysteem', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'uw gegevens te verifieren', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'rekening te beveiligen', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'été bloqué temporairement', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'.pdf.zip', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'.pdf.exe', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'http://www.vindazo.be', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'dog supply', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Tagged@taggedmail.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'mailin.fr', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'@info-ebods.be', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Million EUROS', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Vigarra', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'RNATIONAL LOTTO', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Loterie', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'gagnant', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'de toegang tot uw online-account dreigt te verlopen', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'list-manage.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'SMARTIZIO', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'list-manage1.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'bpost bank Online Access: klik hier', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'bxmg.info', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'online-account dreigt te verlopen', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'alle soorten leningen', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'toegang tot uw online- account', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Vous etes un gagnant', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'AVIS DE RECOMPENSE.pdf', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'be rest assured that the transaction is 100% legal AND risk free.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'prepare agreement document for the sharing ratio', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Received: from [98.139.212.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'My mother died when I was a baby', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Please i need you to help me to transfer the money into your account', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'photoexpert@aliyun.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Content-Type: application/octet-stream;', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'@buddytv.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'return@jx29.epsace.net', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'GetFleetTracking.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'ecoprintsolutions.be', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'bounce@cloudmails.be', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'epsace.net', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'ip=5.196.121.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'sudarshansaur.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'ip=162.222.225', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'from [100.181.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'@mycom.be', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'mail.winstmail.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'noreply@actiemails.nl', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Groeit er mos op uw dak?', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'newsletter.toshiba.eu', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'serveisglobals.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'http://208.51.63', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'humanityagainstisil.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'([72.198.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'cableonline.com.mx ([177.238.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'starweb.net.br ([177.75.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'bpcashtrk.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'moodle', 'TRUE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'We have thousands of women', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'to have sex with', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'someone to have sex with', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'scholes.org', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'F#ckbuddy Tonight', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'BangBuddy', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'looking for casual sexual encount', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'invite from TwoHotChicks', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'ideaxis.com ([217.148.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'orange.es ([92.176', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'optimus.pt ([93.102', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'ollo.com.bd', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'intrum.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Outstanding Account', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'angeldropsltd.com ([103.242.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'HotelPlanner.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'([212.156.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'info@sky-shot.info', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'ispsystem.net ([93.158.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'ttnet.com.tr', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'([119.2.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'ning.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'.net ([212.145.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'boundary=\"\\\\/[a-z0-9A-Z]{4}\\\\/[a-z0-9A-Z]{10}', 'FALSE', 'REGEX', 'GLOBAL', NULL, NULL, 1);
(NULL,'tataidc.co.in ([111.93.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'boundary=--boundary_1_[a-z0-9A-Z]{8}\\\\-[a-z0-9A-Z]{4}\\\\-[a-z0-9A-Z]{4}\\\\-[a-z0-9A-Z]{4}\\\\-[a-z0-9A-Z]{12}', 'FALSE', 'REGEX', 'GLOBAL', NULL, NULL, 1);
(NULL,'boundary=([\"a-z0-9A-Z\\\\-_]*)b1_', 'FALSE', 'REGEX', 'GLOBAL', NULL, NULL, 1);
(NULL,'boundary=([\"a-z0-9A-Z\\\\-]*)_1_', 'FALSE', 'REGEX', 'GLOBAL', NULL, NULL, 1);
(NULL,'info@dollydagger.be', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'vnpt.vn ([14.162', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'vodafonedsl.it ([188.217', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'boundary=\"----=_Part_([0-9]{7})_([0-9]{10}).([0-9]{13})', 'FALSE', 'REGEX', 'GLOBAL', NULL, NULL, 1);
(NULL,'vnpt.vn ([14.181', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'static.gvt.net.br ([191.251.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'http:\\\\/\\\\/([a-zA-Z.0-9]+)\\\\/wp\\\\-content\\\\/cache\\\\/cache\\\\/', 'FALSE', 'REGEX', 'GLOBAL', NULL, NULL, 1);
(NULL,'Salary is \\\\\\$([0-9]+)\\\\-\\\\\\$([0-9]+).', 'FALSE', 'REGEX', 'GLOBAL', NULL, NULL, 1);
(NULL,'http%3A%2F%2F([a-zA-Z0-9]+)\\\\.megahookup', 'FALSE', 'REGEX', 'GLOBAL', NULL, NULL, 1);
(NULL,'@yandex.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'emailbackend.com ([185.133.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'.stream ([160.20', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'([216.240.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'buy now!', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'vectranet.pl ([178.235.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'artbydion.com ([5.230.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'9lives.be', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'netfcf.com ([5.230.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'antagus.de ([94.102.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'acebook', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'pharmacie', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'produits', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'hotcareassist.ru', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'dtemail.net', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'fuller hear', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'Les meilleurs medicaments disponibles', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'niaodei.com ([107.172.104.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'\\\\<base href\\\\=', 'TRUE', 'REGEX', 'GLOBAL', NULL, NULL, 1);
(NULL,'reno-batiments.com', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'resource://', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'vnpt.vn ([14.175.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'I want to be in your bed', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'I am ready for any experiments in bed', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'What would you like to do with me?', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'I want you. Write me', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'I want to experiment in bed with you.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'korbank.pl ([79.110.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'mts-nn.ru ([89.109.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'business.dg-w.de ([185.65.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'bahnhof.se ([94.254.', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'tits', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);
(NULL,'boobs', 'FALSE', 'STRING', 'GLOBAL', NULL, NULL, 1);